CRTLIB LIB(RPGACADEMY) TEXT('RPG Blend Academy training')

CRTSRCPF FILE(RPGACADEMY/QRPGLESRC) RCDLEN(112) TEXT('RPG source members')

ADDPFM FILE(RPGACADEMY/QRPGLESRC) MBR(HELLO) SRCTYPE(RPGLE) TEXT('First RPG program')
